[Master]
license_mask = 0
user_language = 1
mount_cache = false

[GPU]
renderer = "any"
allow_variable_refresh = false
black_bars = false

[Input]
keyboard_mode = "XInput"
keyboard_slot = 0

[Hacks]
protect_zero = false
break_on_unimplemented = false

[CanaryVideo]
vsync_fps = "off"
internal_resolution = "720p"
avpack = ""

[CanaryHacks]
max_queued_frames = 1
