[tool.poetry]
name = "perch"
version = "0.1.0"
description = "Frontend for Xenia Canary"
authors = ["Noah Mattocks"]
packages = [{ include = "launcher" }]

[tool.poetry.dependencies]
python = "^3.13"
PySide6 = "^6.7"